sudo: false

language: php

php:
    - "nightly"

branches:
  only:
    - master

env:
  global:
    - WP_CLI_BIN_DIR=/tmp/wp-cli-phar
    - WP_TEST_URL=http://polylang-cli.dev
  matrix:
    - WP_VERSION=latest

matrix:
  include:
    - php: 5.3
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=trunk
    - php: 7.0
      env: WP_VERSION=latest
  allow_failures:
    - php: nightly
    - php: 5.3

before_script:
  - composer validate
  - bash bin/install-package-tests.sh

script: ./vendor/bin/behat --strict

cache:
  - composer
  - $HOME/.composer/cache

notifications:
  email:
    on_success: never
    on_failure: change
