sudo: false
dist: trusty

language: php

notifications:
  email:
    on_success: never
    on_failure: change

php:
    - "nightly"

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - PATH="$TRAVIS_BUILD_DIR/vendor/bin:$PATH"
    - WP_CLI_BIN_DIR="$TRAVIS_BUILD_DIR/vendor/bin"
  matrix:
    - WP_VERSION=latest

matrix:
  include:
    - php: 5.6
      env: WP_VERSION=latest
    - php: 7.0
      dist: precise
      env: WP_VERSION=latest
    - php: 7.1
      env: WP_VERSION=latest
    - php: 7.2
      env: WP_VERSION=latest
  allow_failures:
    - php: 7.2

before_install:
  - if [[ $TRAVIS_PHP_VERSION != '7.2' ]]; then phpenv config-rm xdebug.ini; fi

install:
  - composer require wp-cli/wp-cli:dev-master
  - composer install
  - bash bin/install-package-tests.sh

before_script:
  - composer validate

script:
  - bash bin/test.sh
